# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xt4kba2ywMrO7X8ZVfX794WykiksK7EF
"""

#1
a = ["Cherry", "Mobil", "1300", "Pink", "4"]
print (a)
a.append("200.000.000")
print (a)
a.append("Suv")
print (a)
a.insert(1, "Avanza")
print (a)

#2
type = """Pilihlah bangun datar yang ingin dihitung
1. Luas Persegi
2. Luas Lingkaran
3. Luas Segitiga"""

pilihan = input(type)

match pilihan :
  case "1" :
    print("Anda memilih 1 yaitu menghitung Luas Persegi")
    Sisi = int(input("Masukan Sisi:"))
    Luas_Persegi = Sisi * Sisi
    print ("hasilnya adalah", Luas_Persegi)
  case "2" :
    print("Anda memilih 2 yaitu menghitung Luas Lingkaran")
    Jari_jari = int(input("Masukan Jari_jari:"))
    Phi = 3.14
    Luas_Lingkaran = Phi * Jari_jari * Jari_jari
    print ("hasilnya adalah", Luas_Lingkaran)
  case "3" :
    print("Anda memilih 3 yaitu menghitung Luas Segitiga")
    Alas = int(input("Masukan Alas:"))
    Tinggi = int(input("Masukan Tinggi"))
    Luas_Segitiga = 1/2 * Alas * Tinggi
    print ("hasilnya adalah", Luas_Segitiga)
  case _:
    print("anda salah memilih pilihan")

